/*
CryptoAPIs

Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

API version: 2.0.0
Contact: developers@cryptoapis.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptoapis

import (
	"encoding/json"
)

// ListLatestMinedBlocksRIBSD2 Dogecoin
type ListLatestMinedBlocksRIBSD2 struct {
	// Represents a specific sub-unit of Doge. Bits have two-decimal precision.
	Bits string `json:"bits"`
	// Represents a hexadecimal number of all the hashes necessary to produce the current chain. E.g., when converting 0000000000000000000000000000000000000000000086859f7a841475b236fd to a decimal you get 635262017308958427068157 hashes, or 635262 exahash
	Chainwork string `json:"chainwork"`
	// Defines the single and final (root) node of a Merkle tree. It is the combined hash of all transactions' hashes that are part of a blockchain block.
	MerkleRoot string `json:"merkleRoot"`
	// Defines the numeric representation of the block size excluding the witness data.
	StrippedSize int32 `json:"strippedSize"`
	// Represents the version of the specific block on the blockchain.
	Version int32 `json:"version"`
	// Represents a measurement to compare the size of different transactions to each other in proportion to the block size limit.
	Weight int32 `json:"weight"`
}

// NewListLatestMinedBlocksRIBSD2 instantiates a new ListLatestMinedBlocksRIBSD2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListLatestMinedBlocksRIBSD2(bits string, chainwork string, merkleRoot string, strippedSize int32, version int32, weight int32) *ListLatestMinedBlocksRIBSD2 {
	this := ListLatestMinedBlocksRIBSD2{}
	this.Bits = bits
	this.Chainwork = chainwork
	this.MerkleRoot = merkleRoot
	this.StrippedSize = strippedSize
	this.Version = version
	this.Weight = weight
	return &this
}

// NewListLatestMinedBlocksRIBSD2WithDefaults instantiates a new ListLatestMinedBlocksRIBSD2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListLatestMinedBlocksRIBSD2WithDefaults() *ListLatestMinedBlocksRIBSD2 {
	this := ListLatestMinedBlocksRIBSD2{}
	return &this
}

// GetBits returns the Bits field value
func (o *ListLatestMinedBlocksRIBSD2) GetBits() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Bits
}

// GetBitsOk returns a tuple with the Bits field value
// and a boolean to check if the value has been set.
func (o *ListLatestMinedBlocksRIBSD2) GetBitsOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Bits, true
}

// SetBits sets field value
func (o *ListLatestMinedBlocksRIBSD2) SetBits(v string) {
	o.Bits = v
}

// GetChainwork returns the Chainwork field value
func (o *ListLatestMinedBlocksRIBSD2) GetChainwork() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Chainwork
}

// GetChainworkOk returns a tuple with the Chainwork field value
// and a boolean to check if the value has been set.
func (o *ListLatestMinedBlocksRIBSD2) GetChainworkOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Chainwork, true
}

// SetChainwork sets field value
func (o *ListLatestMinedBlocksRIBSD2) SetChainwork(v string) {
	o.Chainwork = v
}

// GetMerkleRoot returns the MerkleRoot field value
func (o *ListLatestMinedBlocksRIBSD2) GetMerkleRoot() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MerkleRoot
}

// GetMerkleRootOk returns a tuple with the MerkleRoot field value
// and a boolean to check if the value has been set.
func (o *ListLatestMinedBlocksRIBSD2) GetMerkleRootOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.MerkleRoot, true
}

// SetMerkleRoot sets field value
func (o *ListLatestMinedBlocksRIBSD2) SetMerkleRoot(v string) {
	o.MerkleRoot = v
}

// GetStrippedSize returns the StrippedSize field value
func (o *ListLatestMinedBlocksRIBSD2) GetStrippedSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.StrippedSize
}

// GetStrippedSizeOk returns a tuple with the StrippedSize field value
// and a boolean to check if the value has been set.
func (o *ListLatestMinedBlocksRIBSD2) GetStrippedSizeOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.StrippedSize, true
}

// SetStrippedSize sets field value
func (o *ListLatestMinedBlocksRIBSD2) SetStrippedSize(v int32) {
	o.StrippedSize = v
}

// GetVersion returns the Version field value
func (o *ListLatestMinedBlocksRIBSD2) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *ListLatestMinedBlocksRIBSD2) GetVersionOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *ListLatestMinedBlocksRIBSD2) SetVersion(v int32) {
	o.Version = v
}

// GetWeight returns the Weight field value
func (o *ListLatestMinedBlocksRIBSD2) GetWeight() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Weight
}

// GetWeightOk returns a tuple with the Weight field value
// and a boolean to check if the value has been set.
func (o *ListLatestMinedBlocksRIBSD2) GetWeightOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Weight, true
}

// SetWeight sets field value
func (o *ListLatestMinedBlocksRIBSD2) SetWeight(v int32) {
	o.Weight = v
}

func (o ListLatestMinedBlocksRIBSD2) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["bits"] = o.Bits
	}
	if true {
		toSerialize["chainwork"] = o.Chainwork
	}
	if true {
		toSerialize["merkleRoot"] = o.MerkleRoot
	}
	if true {
		toSerialize["strippedSize"] = o.StrippedSize
	}
	if true {
		toSerialize["version"] = o.Version
	}
	if true {
		toSerialize["weight"] = o.Weight
	}
	return json.Marshal(toSerialize)
}

type NullableListLatestMinedBlocksRIBSD2 struct {
	value *ListLatestMinedBlocksRIBSD2
	isSet bool
}

func (v NullableListLatestMinedBlocksRIBSD2) Get() *ListLatestMinedBlocksRIBSD2 {
	return v.value
}

func (v *NullableListLatestMinedBlocksRIBSD2) Set(val *ListLatestMinedBlocksRIBSD2) {
	v.value = val
	v.isSet = true
}

func (v NullableListLatestMinedBlocksRIBSD2) IsSet() bool {
	return v.isSet
}

func (v *NullableListLatestMinedBlocksRIBSD2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListLatestMinedBlocksRIBSD2(val *ListLatestMinedBlocksRIBSD2) *NullableListLatestMinedBlocksRIBSD2 {
	return &NullableListLatestMinedBlocksRIBSD2{value: val, isSet: true}
}

func (v NullableListLatestMinedBlocksRIBSD2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListLatestMinedBlocksRIBSD2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


