/*
CryptoAPIs

Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

API version: 2021-03-20
Contact: developers@cryptoapis.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptoapis

import (
	"encoding/json"
)

// ListAllAssetsFromAllWalletsRIFungibleTokensInner struct for ListAllAssetsFromAllWalletsRIFungibleTokensInner
type ListAllAssetsFromAllWalletsRIFungibleTokensInner struct {
	// Defines the amount of the fungible tokens.
	Amount string `json:"amount"`
	// Represents the specific blockchain protocol name, e.g. Ethereum, Bitcoin, etc.
	Blockchain string `json:"blockchain"`
	// Defines the specific token identifier. For Bitcoin-based transactions it should be the propertyId and for Ethereum-based transactions - the contract.
	Identifier string `json:"identifier"`
	// Represents the name of the blockchain network used; blockchain networks are usually identical as technology and software, but they differ in data, e.g. - \"mainnet\" is the live network with actual data while networks like \"testnet\", \"ropsten\" are test networks.
	Network string `json:"network"`
	// Defines the symbol of the fungible tokens.
	Symbol string `json:"symbol"`
	// Defines the specific token type.
	Type string `json:"type"`
}

// NewListAllAssetsFromAllWalletsRIFungibleTokensInner instantiates a new ListAllAssetsFromAllWalletsRIFungibleTokensInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListAllAssetsFromAllWalletsRIFungibleTokensInner(amount string, blockchain string, identifier string, network string, symbol string, type_ string) *ListAllAssetsFromAllWalletsRIFungibleTokensInner {
	this := ListAllAssetsFromAllWalletsRIFungibleTokensInner{}
	this.Amount = amount
	this.Blockchain = blockchain
	this.Identifier = identifier
	this.Network = network
	this.Symbol = symbol
	this.Type = type_
	return &this
}

// NewListAllAssetsFromAllWalletsRIFungibleTokensInnerWithDefaults instantiates a new ListAllAssetsFromAllWalletsRIFungibleTokensInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListAllAssetsFromAllWalletsRIFungibleTokensInnerWithDefaults() *ListAllAssetsFromAllWalletsRIFungibleTokensInner {
	this := ListAllAssetsFromAllWalletsRIFungibleTokensInner{}
	return &this
}

// GetAmount returns the Amount field value
func (o *ListAllAssetsFromAllWalletsRIFungibleTokensInner) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *ListAllAssetsFromAllWalletsRIFungibleTokensInner) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *ListAllAssetsFromAllWalletsRIFungibleTokensInner) SetAmount(v string) {
	o.Amount = v
}

// GetBlockchain returns the Blockchain field value
func (o *ListAllAssetsFromAllWalletsRIFungibleTokensInner) GetBlockchain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Blockchain
}

// GetBlockchainOk returns a tuple with the Blockchain field value
// and a boolean to check if the value has been set.
func (o *ListAllAssetsFromAllWalletsRIFungibleTokensInner) GetBlockchainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Blockchain, true
}

// SetBlockchain sets field value
func (o *ListAllAssetsFromAllWalletsRIFungibleTokensInner) SetBlockchain(v string) {
	o.Blockchain = v
}

// GetIdentifier returns the Identifier field value
func (o *ListAllAssetsFromAllWalletsRIFungibleTokensInner) GetIdentifier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value
// and a boolean to check if the value has been set.
func (o *ListAllAssetsFromAllWalletsRIFungibleTokensInner) GetIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Identifier, true
}

// SetIdentifier sets field value
func (o *ListAllAssetsFromAllWalletsRIFungibleTokensInner) SetIdentifier(v string) {
	o.Identifier = v
}

// GetNetwork returns the Network field value
func (o *ListAllAssetsFromAllWalletsRIFungibleTokensInner) GetNetwork() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value
// and a boolean to check if the value has been set.
func (o *ListAllAssetsFromAllWalletsRIFungibleTokensInner) GetNetworkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Network, true
}

// SetNetwork sets field value
func (o *ListAllAssetsFromAllWalletsRIFungibleTokensInner) SetNetwork(v string) {
	o.Network = v
}

// GetSymbol returns the Symbol field value
func (o *ListAllAssetsFromAllWalletsRIFungibleTokensInner) GetSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value
// and a boolean to check if the value has been set.
func (o *ListAllAssetsFromAllWalletsRIFungibleTokensInner) GetSymbolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Symbol, true
}

// SetSymbol sets field value
func (o *ListAllAssetsFromAllWalletsRIFungibleTokensInner) SetSymbol(v string) {
	o.Symbol = v
}

// GetType returns the Type field value
func (o *ListAllAssetsFromAllWalletsRIFungibleTokensInner) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ListAllAssetsFromAllWalletsRIFungibleTokensInner) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ListAllAssetsFromAllWalletsRIFungibleTokensInner) SetType(v string) {
	o.Type = v
}

func (o ListAllAssetsFromAllWalletsRIFungibleTokensInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["amount"] = o.Amount
	}
	if true {
		toSerialize["blockchain"] = o.Blockchain
	}
	if true {
		toSerialize["identifier"] = o.Identifier
	}
	if true {
		toSerialize["network"] = o.Network
	}
	if true {
		toSerialize["symbol"] = o.Symbol
	}
	if true {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableListAllAssetsFromAllWalletsRIFungibleTokensInner struct {
	value *ListAllAssetsFromAllWalletsRIFungibleTokensInner
	isSet bool
}

func (v NullableListAllAssetsFromAllWalletsRIFungibleTokensInner) Get() *ListAllAssetsFromAllWalletsRIFungibleTokensInner {
	return v.value
}

func (v *NullableListAllAssetsFromAllWalletsRIFungibleTokensInner) Set(val *ListAllAssetsFromAllWalletsRIFungibleTokensInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListAllAssetsFromAllWalletsRIFungibleTokensInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListAllAssetsFromAllWalletsRIFungibleTokensInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAllAssetsFromAllWalletsRIFungibleTokensInner(val *ListAllAssetsFromAllWalletsRIFungibleTokensInner) *NullableListAllAssetsFromAllWalletsRIFungibleTokensInner {
	return &NullableListAllAssetsFromAllWalletsRIFungibleTokensInner{value: val, isSet: true}
}

func (v NullableListAllAssetsFromAllWalletsRIFungibleTokensInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAllAssetsFromAllWalletsRIFungibleTokensInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


