/*
 * CryptoAPIs
 *
 * Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * API version: 2.0.0
 * Contact: developers@cryptoapis.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptoapis

import (
	"encoding/json"
	"fmt"
)

// CreateTokensTransactionRequestFromAddressRITokenTypeSpecificData - Represents the specific token data which depends on its type - if it is a Coin or Token.
type CreateTokensTransactionRequestFromAddressRITokenTypeSpecificData struct {
	CreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataBitcoinOmniToken *CreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataBitcoinOmniToken
	CreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataEthereumErc20Token *CreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataEthereumErc20Token
}

// CreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataBitcoinOmniTokenAsCreateTokensTransactionRequestFromAddressRITokenTypeSpecificData is a convenience function that returns CreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataBitcoinOmniToken wrapped in CreateTokensTransactionRequestFromAddressRITokenTypeSpecificData
func CreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataBitcoinOmniTokenAsCreateTokensTransactionRequestFromAddressRITokenTypeSpecificData(v *CreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataBitcoinOmniToken) CreateTokensTransactionRequestFromAddressRITokenTypeSpecificData {
	return CreateTokensTransactionRequestFromAddressRITokenTypeSpecificData{ CreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataBitcoinOmniToken: v}
}

// CreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataEthereumErc20TokenAsCreateTokensTransactionRequestFromAddressRITokenTypeSpecificData is a convenience function that returns CreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataEthereumErc20Token wrapped in CreateTokensTransactionRequestFromAddressRITokenTypeSpecificData
func CreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataEthereumErc20TokenAsCreateTokensTransactionRequestFromAddressRITokenTypeSpecificData(v *CreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataEthereumErc20Token) CreateTokensTransactionRequestFromAddressRITokenTypeSpecificData {
	return CreateTokensTransactionRequestFromAddressRITokenTypeSpecificData{ CreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataEthereumErc20Token: v}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *CreateTokensTransactionRequestFromAddressRITokenTypeSpecificData) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into CreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataBitcoinOmniToken
	err = json.Unmarshal(data, &dst.CreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataBitcoinOmniToken)
	if err == nil {
		jsonCreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataBitcoinOmniToken, _ := json.Marshal(dst.CreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataBitcoinOmniToken)
		if string(jsonCreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataBitcoinOmniToken) == "{}" { // empty struct
			dst.CreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataBitcoinOmniToken = nil
		} else {
			match++
		}
	} else {
		dst.CreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataBitcoinOmniToken = nil
	}

	// try to unmarshal data into CreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataEthereumErc20Token
	err = json.Unmarshal(data, &dst.CreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataEthereumErc20Token)
	if err == nil {
		jsonCreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataEthereumErc20Token, _ := json.Marshal(dst.CreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataEthereumErc20Token)
		if string(jsonCreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataEthereumErc20Token) == "{}" { // empty struct
			dst.CreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataEthereumErc20Token = nil
		} else {
			match++
		}
	} else {
		dst.CreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataEthereumErc20Token = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.CreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataBitcoinOmniToken = nil
		dst.CreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataEthereumErc20Token = nil

		return fmt.Errorf("Data matches more than one schema in oneOf(CreateTokensTransactionRequestFromAddressRITokenTypeSpecificData)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("Data failed to match schemas in oneOf(CreateTokensTransactionRequestFromAddressRITokenTypeSpecificData)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CreateTokensTransactionRequestFromAddressRITokenTypeSpecificData) MarshalJSON() ([]byte, error) {
	if src.CreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataBitcoinOmniToken != nil {
		return json.Marshal(&src.CreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataBitcoinOmniToken)
	}

	if src.CreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataEthereumErc20Token != nil {
		return json.Marshal(&src.CreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataEthereumErc20Token)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CreateTokensTransactionRequestFromAddressRITokenTypeSpecificData) GetActualInstance() (interface{}) {
	if obj.CreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataBitcoinOmniToken != nil {
		return obj.CreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataBitcoinOmniToken
	}

	if obj.CreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataEthereumErc20Token != nil {
		return obj.CreateTokensTransactionRequestFromAddressRITokenTypeSpecificDataEthereumErc20Token
	}

	// all schemas are nil
	return nil
}

type NullableCreateTokensTransactionRequestFromAddressRITokenTypeSpecificData struct {
	value *CreateTokensTransactionRequestFromAddressRITokenTypeSpecificData
	isSet bool
}

func (v NullableCreateTokensTransactionRequestFromAddressRITokenTypeSpecificData) Get() *CreateTokensTransactionRequestFromAddressRITokenTypeSpecificData {
	return v.value
}

func (v *NullableCreateTokensTransactionRequestFromAddressRITokenTypeSpecificData) Set(val *CreateTokensTransactionRequestFromAddressRITokenTypeSpecificData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTokensTransactionRequestFromAddressRITokenTypeSpecificData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTokensTransactionRequestFromAddressRITokenTypeSpecificData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTokensTransactionRequestFromAddressRITokenTypeSpecificData(val *CreateTokensTransactionRequestFromAddressRITokenTypeSpecificData) *NullableCreateTokensTransactionRequestFromAddressRITokenTypeSpecificData {
	return &NullableCreateTokensTransactionRequestFromAddressRITokenTypeSpecificData{value: val, isSet: true}
}

func (v NullableCreateTokensTransactionRequestFromAddressRITokenTypeSpecificData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTokensTransactionRequestFromAddressRITokenTypeSpecificData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


