/*
CryptoAPIs

Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

API version: 2021-03-20
Contact: developers@cryptoapis.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptoapis

import (
	"encoding/json"
)

// GetXRPRippleTransactionDetailsByTransactionIDRI struct for GetXRPRippleTransactionDetailsByTransactionIDRI
type GetXRPRippleTransactionDetailsByTransactionIDRI struct {
	// Represents additional data that may be needed.
	AdditionalData string `json:"additionalData"`
	DestinationTag *int64 `json:"destinationTag,omitempty"`
	// Defines the index of the transaction, i.e. the consecutive place it takes in the blockchain.
	Index string `json:"index"`
	// Represents the hash of the block where this transaction was mined/confirmed for first time. The hash is defined as a cryptographic digital fingerprint made by hashing the block header twice through the SHA256 algorithm.
	MinedInBlockHash string `json:"minedInBlockHash"`
	// Represents the hight of the block where this transaction was mined/confirmed for first time. The height is defined as the number of blocks in the blockchain preceding this specific block.
	MinedInBlockHeight string `json:"minedInBlockHeight"`
	Offer GetXRPRippleTransactionDetailsByTransactionIDRIOffer `json:"offer"`
	Receive GetXRPRippleTransactionDetailsByTransactionIDRIReceive `json:"receive"`
	// Represents an object of addresses that receive the transactions.
	Recipients []GetXRPRippleTransactionDetailsByTransactionIDRIRecipientsInner `json:"recipients"`
	// Represents an object of addresses that provide the funds.
	Senders []GetXRPRippleTransactionDetailsByTransactionIDRISendersInner `json:"senders"`
	// Defines the transaction input's sequence as an integer, which is is used when transactions are replaced with newer versions before LockTime.
	Sequence int64 `json:"sequence"`
	// Defines the status of the transaction.
	Status *string `json:"status,omitempty"`
	// Defines the exact date/time in Unix Timestamp when this transaction was mined, confirmed or first seen in Mempool, if it is unconfirmed.
	Timestamp int32 `json:"timestamp"`
	// Represents the same as `transactionId` for account-based protocols like Ethereum, while it could be different in UTXO-based protocols like Bitcoin. E.g., in UTXO-based protocols `hash` is different from `transactionId` for SegWit transactions.
	TransactionHash string `json:"transactionHash"`
	// Defines the type of the transaction.
	Type string `json:"type"`
	Fee GetXRPRippleTransactionDetailsByTransactionIDRIFee `json:"fee"`
	Value GetXRPRippleTransactionDetailsByTransactionIDRIValue `json:"value"`
}

// NewGetXRPRippleTransactionDetailsByTransactionIDRI instantiates a new GetXRPRippleTransactionDetailsByTransactionIDRI object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetXRPRippleTransactionDetailsByTransactionIDRI(additionalData string, index string, minedInBlockHash string, minedInBlockHeight string, offer GetXRPRippleTransactionDetailsByTransactionIDRIOffer, receive GetXRPRippleTransactionDetailsByTransactionIDRIReceive, recipients []GetXRPRippleTransactionDetailsByTransactionIDRIRecipientsInner, senders []GetXRPRippleTransactionDetailsByTransactionIDRISendersInner, sequence int64, timestamp int32, transactionHash string, type_ string, fee GetXRPRippleTransactionDetailsByTransactionIDRIFee, value GetXRPRippleTransactionDetailsByTransactionIDRIValue) *GetXRPRippleTransactionDetailsByTransactionIDRI {
	this := GetXRPRippleTransactionDetailsByTransactionIDRI{}
	this.AdditionalData = additionalData
	this.Index = index
	this.MinedInBlockHash = minedInBlockHash
	this.MinedInBlockHeight = minedInBlockHeight
	this.Offer = offer
	this.Receive = receive
	this.Recipients = recipients
	this.Senders = senders
	this.Sequence = sequence
	this.Timestamp = timestamp
	this.TransactionHash = transactionHash
	this.Type = type_
	this.Fee = fee
	this.Value = value
	return &this
}

// NewGetXRPRippleTransactionDetailsByTransactionIDRIWithDefaults instantiates a new GetXRPRippleTransactionDetailsByTransactionIDRI object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetXRPRippleTransactionDetailsByTransactionIDRIWithDefaults() *GetXRPRippleTransactionDetailsByTransactionIDRI {
	this := GetXRPRippleTransactionDetailsByTransactionIDRI{}
	return &this
}

// GetAdditionalData returns the AdditionalData field value
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) GetAdditionalData() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AdditionalData
}

// GetAdditionalDataOk returns a tuple with the AdditionalData field value
// and a boolean to check if the value has been set.
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) GetAdditionalDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AdditionalData, true
}

// SetAdditionalData sets field value
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) SetAdditionalData(v string) {
	o.AdditionalData = v
}

// GetDestinationTag returns the DestinationTag field value if set, zero value otherwise.
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) GetDestinationTag() int64 {
	if o == nil || o.DestinationTag == nil {
		var ret int64
		return ret
	}
	return *o.DestinationTag
}

// GetDestinationTagOk returns a tuple with the DestinationTag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) GetDestinationTagOk() (*int64, bool) {
	if o == nil || o.DestinationTag == nil {
		return nil, false
	}
	return o.DestinationTag, true
}

// HasDestinationTag returns a boolean if a field has been set.
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) HasDestinationTag() bool {
	if o != nil && o.DestinationTag != nil {
		return true
	}

	return false
}

// SetDestinationTag gets a reference to the given int64 and assigns it to the DestinationTag field.
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) SetDestinationTag(v int64) {
	o.DestinationTag = &v
}

// GetIndex returns the Index field value
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) GetIndex() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Index
}

// GetIndexOk returns a tuple with the Index field value
// and a boolean to check if the value has been set.
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) GetIndexOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Index, true
}

// SetIndex sets field value
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) SetIndex(v string) {
	o.Index = v
}

// GetMinedInBlockHash returns the MinedInBlockHash field value
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) GetMinedInBlockHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MinedInBlockHash
}

// GetMinedInBlockHashOk returns a tuple with the MinedInBlockHash field value
// and a boolean to check if the value has been set.
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) GetMinedInBlockHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinedInBlockHash, true
}

// SetMinedInBlockHash sets field value
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) SetMinedInBlockHash(v string) {
	o.MinedInBlockHash = v
}

// GetMinedInBlockHeight returns the MinedInBlockHeight field value
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) GetMinedInBlockHeight() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MinedInBlockHeight
}

// GetMinedInBlockHeightOk returns a tuple with the MinedInBlockHeight field value
// and a boolean to check if the value has been set.
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) GetMinedInBlockHeightOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinedInBlockHeight, true
}

// SetMinedInBlockHeight sets field value
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) SetMinedInBlockHeight(v string) {
	o.MinedInBlockHeight = v
}

// GetOffer returns the Offer field value
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) GetOffer() GetXRPRippleTransactionDetailsByTransactionIDRIOffer {
	if o == nil {
		var ret GetXRPRippleTransactionDetailsByTransactionIDRIOffer
		return ret
	}

	return o.Offer
}

// GetOfferOk returns a tuple with the Offer field value
// and a boolean to check if the value has been set.
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) GetOfferOk() (*GetXRPRippleTransactionDetailsByTransactionIDRIOffer, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Offer, true
}

// SetOffer sets field value
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) SetOffer(v GetXRPRippleTransactionDetailsByTransactionIDRIOffer) {
	o.Offer = v
}

// GetReceive returns the Receive field value
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) GetReceive() GetXRPRippleTransactionDetailsByTransactionIDRIReceive {
	if o == nil {
		var ret GetXRPRippleTransactionDetailsByTransactionIDRIReceive
		return ret
	}

	return o.Receive
}

// GetReceiveOk returns a tuple with the Receive field value
// and a boolean to check if the value has been set.
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) GetReceiveOk() (*GetXRPRippleTransactionDetailsByTransactionIDRIReceive, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Receive, true
}

// SetReceive sets field value
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) SetReceive(v GetXRPRippleTransactionDetailsByTransactionIDRIReceive) {
	o.Receive = v
}

// GetRecipients returns the Recipients field value
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) GetRecipients() []GetXRPRippleTransactionDetailsByTransactionIDRIRecipientsInner {
	if o == nil {
		var ret []GetXRPRippleTransactionDetailsByTransactionIDRIRecipientsInner
		return ret
	}

	return o.Recipients
}

// GetRecipientsOk returns a tuple with the Recipients field value
// and a boolean to check if the value has been set.
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) GetRecipientsOk() ([]GetXRPRippleTransactionDetailsByTransactionIDRIRecipientsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Recipients, true
}

// SetRecipients sets field value
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) SetRecipients(v []GetXRPRippleTransactionDetailsByTransactionIDRIRecipientsInner) {
	o.Recipients = v
}

// GetSenders returns the Senders field value
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) GetSenders() []GetXRPRippleTransactionDetailsByTransactionIDRISendersInner {
	if o == nil {
		var ret []GetXRPRippleTransactionDetailsByTransactionIDRISendersInner
		return ret
	}

	return o.Senders
}

// GetSendersOk returns a tuple with the Senders field value
// and a boolean to check if the value has been set.
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) GetSendersOk() ([]GetXRPRippleTransactionDetailsByTransactionIDRISendersInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Senders, true
}

// SetSenders sets field value
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) SetSenders(v []GetXRPRippleTransactionDetailsByTransactionIDRISendersInner) {
	o.Senders = v
}

// GetSequence returns the Sequence field value
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) GetSequence() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Sequence
}

// GetSequenceOk returns a tuple with the Sequence field value
// and a boolean to check if the value has been set.
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) GetSequenceOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sequence, true
}

// SetSequence sets field value
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) SetSequence(v int64) {
	o.Sequence = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) SetStatus(v string) {
	o.Status = &v
}

// GetTimestamp returns the Timestamp field value
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) GetTimestamp() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) GetTimestampOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) SetTimestamp(v int32) {
	o.Timestamp = v
}

// GetTransactionHash returns the TransactionHash field value
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) GetTransactionHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransactionHash
}

// GetTransactionHashOk returns a tuple with the TransactionHash field value
// and a boolean to check if the value has been set.
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) GetTransactionHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransactionHash, true
}

// SetTransactionHash sets field value
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) SetTransactionHash(v string) {
	o.TransactionHash = v
}

// GetType returns the Type field value
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) SetType(v string) {
	o.Type = v
}

// GetFee returns the Fee field value
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) GetFee() GetXRPRippleTransactionDetailsByTransactionIDRIFee {
	if o == nil {
		var ret GetXRPRippleTransactionDetailsByTransactionIDRIFee
		return ret
	}

	return o.Fee
}

// GetFeeOk returns a tuple with the Fee field value
// and a boolean to check if the value has been set.
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) GetFeeOk() (*GetXRPRippleTransactionDetailsByTransactionIDRIFee, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Fee, true
}

// SetFee sets field value
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) SetFee(v GetXRPRippleTransactionDetailsByTransactionIDRIFee) {
	o.Fee = v
}

// GetValue returns the Value field value
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) GetValue() GetXRPRippleTransactionDetailsByTransactionIDRIValue {
	if o == nil {
		var ret GetXRPRippleTransactionDetailsByTransactionIDRIValue
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) GetValueOk() (*GetXRPRippleTransactionDetailsByTransactionIDRIValue, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *GetXRPRippleTransactionDetailsByTransactionIDRI) SetValue(v GetXRPRippleTransactionDetailsByTransactionIDRIValue) {
	o.Value = v
}

func (o GetXRPRippleTransactionDetailsByTransactionIDRI) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["additionalData"] = o.AdditionalData
	}
	if o.DestinationTag != nil {
		toSerialize["destinationTag"] = o.DestinationTag
	}
	if true {
		toSerialize["index"] = o.Index
	}
	if true {
		toSerialize["minedInBlockHash"] = o.MinedInBlockHash
	}
	if true {
		toSerialize["minedInBlockHeight"] = o.MinedInBlockHeight
	}
	if true {
		toSerialize["offer"] = o.Offer
	}
	if true {
		toSerialize["receive"] = o.Receive
	}
	if true {
		toSerialize["recipients"] = o.Recipients
	}
	if true {
		toSerialize["senders"] = o.Senders
	}
	if true {
		toSerialize["sequence"] = o.Sequence
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if true {
		toSerialize["timestamp"] = o.Timestamp
	}
	if true {
		toSerialize["transactionHash"] = o.TransactionHash
	}
	if true {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["fee"] = o.Fee
	}
	if true {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableGetXRPRippleTransactionDetailsByTransactionIDRI struct {
	value *GetXRPRippleTransactionDetailsByTransactionIDRI
	isSet bool
}

func (v NullableGetXRPRippleTransactionDetailsByTransactionIDRI) Get() *GetXRPRippleTransactionDetailsByTransactionIDRI {
	return v.value
}

func (v *NullableGetXRPRippleTransactionDetailsByTransactionIDRI) Set(val *GetXRPRippleTransactionDetailsByTransactionIDRI) {
	v.value = val
	v.isSet = true
}

func (v NullableGetXRPRippleTransactionDetailsByTransactionIDRI) IsSet() bool {
	return v.isSet
}

func (v *NullableGetXRPRippleTransactionDetailsByTransactionIDRI) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetXRPRippleTransactionDetailsByTransactionIDRI(val *GetXRPRippleTransactionDetailsByTransactionIDRI) *NullableGetXRPRippleTransactionDetailsByTransactionIDRI {
	return &NullableGetXRPRippleTransactionDetailsByTransactionIDRI{value: val, isSet: true}
}

func (v NullableGetXRPRippleTransactionDetailsByTransactionIDRI) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetXRPRippleTransactionDetailsByTransactionIDRI) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


