/*
CryptoAPIs

Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

API version: 2.0.0
Contact: developers@cryptoapis.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptoapis

import (
	"encoding/json"
)

// GetAddressDetailsFromCallbackRITotalReceived struct for GetAddressDetailsFromCallbackRITotalReceived
type GetAddressDetailsFromCallbackRITotalReceived struct {
	// Defines the total amount of all coins received to the address, based on confirmed transactions.
	Amount *string `json:"amount,omitempty"`
	// Represents the unit of the total received amount.
	Unit *string `json:"unit,omitempty"`
}

// NewGetAddressDetailsFromCallbackRITotalReceived instantiates a new GetAddressDetailsFromCallbackRITotalReceived object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAddressDetailsFromCallbackRITotalReceived() *GetAddressDetailsFromCallbackRITotalReceived {
	this := GetAddressDetailsFromCallbackRITotalReceived{}
	return &this
}

// NewGetAddressDetailsFromCallbackRITotalReceivedWithDefaults instantiates a new GetAddressDetailsFromCallbackRITotalReceived object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAddressDetailsFromCallbackRITotalReceivedWithDefaults() *GetAddressDetailsFromCallbackRITotalReceived {
	this := GetAddressDetailsFromCallbackRITotalReceived{}
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *GetAddressDetailsFromCallbackRITotalReceived) GetAmount() string {
	if o == nil || o.Amount == nil {
		var ret string
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAddressDetailsFromCallbackRITotalReceived) GetAmountOk() (*string, bool) {
	if o == nil || o.Amount == nil {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *GetAddressDetailsFromCallbackRITotalReceived) HasAmount() bool {
	if o != nil && o.Amount != nil {
		return true
	}

	return false
}

// SetAmount gets a reference to the given string and assigns it to the Amount field.
func (o *GetAddressDetailsFromCallbackRITotalReceived) SetAmount(v string) {
	o.Amount = &v
}

// GetUnit returns the Unit field value if set, zero value otherwise.
func (o *GetAddressDetailsFromCallbackRITotalReceived) GetUnit() string {
	if o == nil || o.Unit == nil {
		var ret string
		return ret
	}
	return *o.Unit
}

// GetUnitOk returns a tuple with the Unit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAddressDetailsFromCallbackRITotalReceived) GetUnitOk() (*string, bool) {
	if o == nil || o.Unit == nil {
		return nil, false
	}
	return o.Unit, true
}

// HasUnit returns a boolean if a field has been set.
func (o *GetAddressDetailsFromCallbackRITotalReceived) HasUnit() bool {
	if o != nil && o.Unit != nil {
		return true
	}

	return false
}

// SetUnit gets a reference to the given string and assigns it to the Unit field.
func (o *GetAddressDetailsFromCallbackRITotalReceived) SetUnit(v string) {
	o.Unit = &v
}

func (o GetAddressDetailsFromCallbackRITotalReceived) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Amount != nil {
		toSerialize["amount"] = o.Amount
	}
	if o.Unit != nil {
		toSerialize["unit"] = o.Unit
	}
	return json.Marshal(toSerialize)
}

type NullableGetAddressDetailsFromCallbackRITotalReceived struct {
	value *GetAddressDetailsFromCallbackRITotalReceived
	isSet bool
}

func (v NullableGetAddressDetailsFromCallbackRITotalReceived) Get() *GetAddressDetailsFromCallbackRITotalReceived {
	return v.value
}

func (v *NullableGetAddressDetailsFromCallbackRITotalReceived) Set(val *GetAddressDetailsFromCallbackRITotalReceived) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAddressDetailsFromCallbackRITotalReceived) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAddressDetailsFromCallbackRITotalReceived) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAddressDetailsFromCallbackRITotalReceived(val *GetAddressDetailsFromCallbackRITotalReceived) *NullableGetAddressDetailsFromCallbackRITotalReceived {
	return &NullableGetAddressDetailsFromCallbackRITotalReceived{value: val, isSet: true}
}

func (v NullableGetAddressDetailsFromCallbackRITotalReceived) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAddressDetailsFromCallbackRITotalReceived) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


