/*
 * CryptoAPIs
 *
 * Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * API version: 2.0.0
 * Contact: developers@cryptoapis.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptoapis

import (
	"encoding/json"
)

// AddressTokensTransactionUnconfirmedOmnilayertoken omniLayerToken
type AddressTokensTransactionUnconfirmedOmnilayertoken struct {
	// Specifies the name of the token.
	Name string `json:"name"`
	// Defines the ID of the property for Omni Layer.
	PropertyId string `json:"propertyId"`
	// Defines the type of the transaction made.
	TransactionType string `json:"transactionType"`
	// The transaction ID used to create the token.
	CreatedByTransactionId string `json:"createdByTransactionId"`
	// Defines the amount of tokens sent with the transaction that is pending confirmation.
	Amount string `json:"amount"`
}

// NewAddressTokensTransactionUnconfirmedOmnilayertoken instantiates a new AddressTokensTransactionUnconfirmedOmnilayertoken object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddressTokensTransactionUnconfirmedOmnilayertoken(name string, propertyId string, transactionType string, createdByTransactionId string, amount string) *AddressTokensTransactionUnconfirmedOmnilayertoken {
	this := AddressTokensTransactionUnconfirmedOmnilayertoken{}
	this.Name = name
	this.PropertyId = propertyId
	this.TransactionType = transactionType
	this.CreatedByTransactionId = createdByTransactionId
	this.Amount = amount
	return &this
}

// NewAddressTokensTransactionUnconfirmedOmnilayertokenWithDefaults instantiates a new AddressTokensTransactionUnconfirmedOmnilayertoken object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddressTokensTransactionUnconfirmedOmnilayertokenWithDefaults() *AddressTokensTransactionUnconfirmedOmnilayertoken {
	this := AddressTokensTransactionUnconfirmedOmnilayertoken{}
	return &this
}

// GetName returns the Name field value
func (o *AddressTokensTransactionUnconfirmedOmnilayertoken) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AddressTokensTransactionUnconfirmedOmnilayertoken) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AddressTokensTransactionUnconfirmedOmnilayertoken) SetName(v string) {
	o.Name = v
}

// GetPropertyId returns the PropertyId field value
func (o *AddressTokensTransactionUnconfirmedOmnilayertoken) GetPropertyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PropertyId
}

// GetPropertyIdOk returns a tuple with the PropertyId field value
// and a boolean to check if the value has been set.
func (o *AddressTokensTransactionUnconfirmedOmnilayertoken) GetPropertyIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PropertyId, true
}

// SetPropertyId sets field value
func (o *AddressTokensTransactionUnconfirmedOmnilayertoken) SetPropertyId(v string) {
	o.PropertyId = v
}

// GetTransactionType returns the TransactionType field value
func (o *AddressTokensTransactionUnconfirmedOmnilayertoken) GetTransactionType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransactionType
}

// GetTransactionTypeOk returns a tuple with the TransactionType field value
// and a boolean to check if the value has been set.
func (o *AddressTokensTransactionUnconfirmedOmnilayertoken) GetTransactionTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.TransactionType, true
}

// SetTransactionType sets field value
func (o *AddressTokensTransactionUnconfirmedOmnilayertoken) SetTransactionType(v string) {
	o.TransactionType = v
}

// GetCreatedByTransactionId returns the CreatedByTransactionId field value
func (o *AddressTokensTransactionUnconfirmedOmnilayertoken) GetCreatedByTransactionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedByTransactionId
}

// GetCreatedByTransactionIdOk returns a tuple with the CreatedByTransactionId field value
// and a boolean to check if the value has been set.
func (o *AddressTokensTransactionUnconfirmedOmnilayertoken) GetCreatedByTransactionIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CreatedByTransactionId, true
}

// SetCreatedByTransactionId sets field value
func (o *AddressTokensTransactionUnconfirmedOmnilayertoken) SetCreatedByTransactionId(v string) {
	o.CreatedByTransactionId = v
}

// GetAmount returns the Amount field value
func (o *AddressTokensTransactionUnconfirmedOmnilayertoken) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *AddressTokensTransactionUnconfirmedOmnilayertoken) GetAmountOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *AddressTokensTransactionUnconfirmedOmnilayertoken) SetAmount(v string) {
	o.Amount = v
}

func (o AddressTokensTransactionUnconfirmedOmnilayertoken) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["propertyId"] = o.PropertyId
	}
	if true {
		toSerialize["transactionType"] = o.TransactionType
	}
	if true {
		toSerialize["createdByTransactionId"] = o.CreatedByTransactionId
	}
	if true {
		toSerialize["amount"] = o.Amount
	}
	return json.Marshal(toSerialize)
}

type NullableAddressTokensTransactionUnconfirmedOmnilayertoken struct {
	value *AddressTokensTransactionUnconfirmedOmnilayertoken
	isSet bool
}

func (v NullableAddressTokensTransactionUnconfirmedOmnilayertoken) Get() *AddressTokensTransactionUnconfirmedOmnilayertoken {
	return v.value
}

func (v *NullableAddressTokensTransactionUnconfirmedOmnilayertoken) Set(val *AddressTokensTransactionUnconfirmedOmnilayertoken) {
	v.value = val
	v.isSet = true
}

func (v NullableAddressTokensTransactionUnconfirmedOmnilayertoken) IsSet() bool {
	return v.isSet
}

func (v *NullableAddressTokensTransactionUnconfirmedOmnilayertoken) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddressTokensTransactionUnconfirmedOmnilayertoken(val *AddressTokensTransactionUnconfirmedOmnilayertoken) *NullableAddressTokensTransactionUnconfirmedOmnilayertoken {
	return &NullableAddressTokensTransactionUnconfirmedOmnilayertoken{value: val, isSet: true}
}

func (v NullableAddressTokensTransactionUnconfirmedOmnilayertoken) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddressTokensTransactionUnconfirmedOmnilayertoken) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


