/*
CryptoAPIs

Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

API version: 2.0.0
Contact: developers@cryptoapis.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptoapis

import (
	"encoding/json"
)

// CreateCoinsTransactionFromAddressForWholeAmountRBData struct for CreateCoinsTransactionFromAddressForWholeAmountRBData
type CreateCoinsTransactionFromAddressForWholeAmountRBData struct {
	Item CreateCoinsTransactionFromAddressForWholeAmountRBDataItem `json:"item"`
}

// NewCreateCoinsTransactionFromAddressForWholeAmountRBData instantiates a new CreateCoinsTransactionFromAddressForWholeAmountRBData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCoinsTransactionFromAddressForWholeAmountRBData(item CreateCoinsTransactionFromAddressForWholeAmountRBDataItem) *CreateCoinsTransactionFromAddressForWholeAmountRBData {
	this := CreateCoinsTransactionFromAddressForWholeAmountRBData{}
	this.Item = item
	return &this
}

// NewCreateCoinsTransactionFromAddressForWholeAmountRBDataWithDefaults instantiates a new CreateCoinsTransactionFromAddressForWholeAmountRBData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCoinsTransactionFromAddressForWholeAmountRBDataWithDefaults() *CreateCoinsTransactionFromAddressForWholeAmountRBData {
	this := CreateCoinsTransactionFromAddressForWholeAmountRBData{}
	return &this
}

// GetItem returns the Item field value
func (o *CreateCoinsTransactionFromAddressForWholeAmountRBData) GetItem() CreateCoinsTransactionFromAddressForWholeAmountRBDataItem {
	if o == nil {
		var ret CreateCoinsTransactionFromAddressForWholeAmountRBDataItem
		return ret
	}

	return o.Item
}

// GetItemOk returns a tuple with the Item field value
// and a boolean to check if the value has been set.
func (o *CreateCoinsTransactionFromAddressForWholeAmountRBData) GetItemOk() (*CreateCoinsTransactionFromAddressForWholeAmountRBDataItem, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Item, true
}

// SetItem sets field value
func (o *CreateCoinsTransactionFromAddressForWholeAmountRBData) SetItem(v CreateCoinsTransactionFromAddressForWholeAmountRBDataItem) {
	o.Item = v
}

func (o CreateCoinsTransactionFromAddressForWholeAmountRBData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["item"] = o.Item
	}
	return json.Marshal(toSerialize)
}

type NullableCreateCoinsTransactionFromAddressForWholeAmountRBData struct {
	value *CreateCoinsTransactionFromAddressForWholeAmountRBData
	isSet bool
}

func (v NullableCreateCoinsTransactionFromAddressForWholeAmountRBData) Get() *CreateCoinsTransactionFromAddressForWholeAmountRBData {
	return v.value
}

func (v *NullableCreateCoinsTransactionFromAddressForWholeAmountRBData) Set(val *CreateCoinsTransactionFromAddressForWholeAmountRBData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCoinsTransactionFromAddressForWholeAmountRBData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCoinsTransactionFromAddressForWholeAmountRBData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCoinsTransactionFromAddressForWholeAmountRBData(val *CreateCoinsTransactionFromAddressForWholeAmountRBData) *NullableCreateCoinsTransactionFromAddressForWholeAmountRBData {
	return &NullableCreateCoinsTransactionFromAddressForWholeAmountRBData{value: val, isSet: true}
}

func (v NullableCreateCoinsTransactionFromAddressForWholeAmountRBData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCoinsTransactionFromAddressForWholeAmountRBData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


