/*
CryptoAPIs

Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

API version: 2021-03-20
Contact: developers@cryptoapis.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptoapis

import (
	"encoding/json"
	"fmt"
)

// DeriveAndSyncNewChangeAddressesE400 - struct for DeriveAndSyncNewChangeAddressesE400
type DeriveAndSyncNewChangeAddressesE400 struct {
	InvalidBlockchain *InvalidBlockchain
	InvalidNetwork *InvalidNetwork
	InvalidPagination *InvalidPagination
	InvalidXpub *InvalidXpub
	LimitGreaterThanAllowed *LimitGreaterThanAllowed
	UriNotFound *UriNotFound
}

// InvalidBlockchainAsDeriveAndSyncNewChangeAddressesE400 is a convenience function that returns InvalidBlockchain wrapped in DeriveAndSyncNewChangeAddressesE400
func InvalidBlockchainAsDeriveAndSyncNewChangeAddressesE400(v *InvalidBlockchain) DeriveAndSyncNewChangeAddressesE400 {
	return DeriveAndSyncNewChangeAddressesE400{
		InvalidBlockchain: v,
	}
}

// InvalidNetworkAsDeriveAndSyncNewChangeAddressesE400 is a convenience function that returns InvalidNetwork wrapped in DeriveAndSyncNewChangeAddressesE400
func InvalidNetworkAsDeriveAndSyncNewChangeAddressesE400(v *InvalidNetwork) DeriveAndSyncNewChangeAddressesE400 {
	return DeriveAndSyncNewChangeAddressesE400{
		InvalidNetwork: v,
	}
}

// InvalidPaginationAsDeriveAndSyncNewChangeAddressesE400 is a convenience function that returns InvalidPagination wrapped in DeriveAndSyncNewChangeAddressesE400
func InvalidPaginationAsDeriveAndSyncNewChangeAddressesE400(v *InvalidPagination) DeriveAndSyncNewChangeAddressesE400 {
	return DeriveAndSyncNewChangeAddressesE400{
		InvalidPagination: v,
	}
}

// InvalidXpubAsDeriveAndSyncNewChangeAddressesE400 is a convenience function that returns InvalidXpub wrapped in DeriveAndSyncNewChangeAddressesE400
func InvalidXpubAsDeriveAndSyncNewChangeAddressesE400(v *InvalidXpub) DeriveAndSyncNewChangeAddressesE400 {
	return DeriveAndSyncNewChangeAddressesE400{
		InvalidXpub: v,
	}
}

// LimitGreaterThanAllowedAsDeriveAndSyncNewChangeAddressesE400 is a convenience function that returns LimitGreaterThanAllowed wrapped in DeriveAndSyncNewChangeAddressesE400
func LimitGreaterThanAllowedAsDeriveAndSyncNewChangeAddressesE400(v *LimitGreaterThanAllowed) DeriveAndSyncNewChangeAddressesE400 {
	return DeriveAndSyncNewChangeAddressesE400{
		LimitGreaterThanAllowed: v,
	}
}

// UriNotFoundAsDeriveAndSyncNewChangeAddressesE400 is a convenience function that returns UriNotFound wrapped in DeriveAndSyncNewChangeAddressesE400
func UriNotFoundAsDeriveAndSyncNewChangeAddressesE400(v *UriNotFound) DeriveAndSyncNewChangeAddressesE400 {
	return DeriveAndSyncNewChangeAddressesE400{
		UriNotFound: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *DeriveAndSyncNewChangeAddressesE400) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into InvalidBlockchain
	err = newStrictDecoder(data).Decode(&dst.InvalidBlockchain)
	if err == nil {
		jsonInvalidBlockchain, _ := json.Marshal(dst.InvalidBlockchain)
		if string(jsonInvalidBlockchain) == "{}" { // empty struct
			dst.InvalidBlockchain = nil
		} else {
			match++
		}
	} else {
		dst.InvalidBlockchain = nil
	}

	// try to unmarshal data into InvalidNetwork
	err = newStrictDecoder(data).Decode(&dst.InvalidNetwork)
	if err == nil {
		jsonInvalidNetwork, _ := json.Marshal(dst.InvalidNetwork)
		if string(jsonInvalidNetwork) == "{}" { // empty struct
			dst.InvalidNetwork = nil
		} else {
			match++
		}
	} else {
		dst.InvalidNetwork = nil
	}

	// try to unmarshal data into InvalidPagination
	err = newStrictDecoder(data).Decode(&dst.InvalidPagination)
	if err == nil {
		jsonInvalidPagination, _ := json.Marshal(dst.InvalidPagination)
		if string(jsonInvalidPagination) == "{}" { // empty struct
			dst.InvalidPagination = nil
		} else {
			match++
		}
	} else {
		dst.InvalidPagination = nil
	}

	// try to unmarshal data into InvalidXpub
	err = newStrictDecoder(data).Decode(&dst.InvalidXpub)
	if err == nil {
		jsonInvalidXpub, _ := json.Marshal(dst.InvalidXpub)
		if string(jsonInvalidXpub) == "{}" { // empty struct
			dst.InvalidXpub = nil
		} else {
			match++
		}
	} else {
		dst.InvalidXpub = nil
	}

	// try to unmarshal data into LimitGreaterThanAllowed
	err = newStrictDecoder(data).Decode(&dst.LimitGreaterThanAllowed)
	if err == nil {
		jsonLimitGreaterThanAllowed, _ := json.Marshal(dst.LimitGreaterThanAllowed)
		if string(jsonLimitGreaterThanAllowed) == "{}" { // empty struct
			dst.LimitGreaterThanAllowed = nil
		} else {
			match++
		}
	} else {
		dst.LimitGreaterThanAllowed = nil
	}

	// try to unmarshal data into UriNotFound
	err = newStrictDecoder(data).Decode(&dst.UriNotFound)
	if err == nil {
		jsonUriNotFound, _ := json.Marshal(dst.UriNotFound)
		if string(jsonUriNotFound) == "{}" { // empty struct
			dst.UriNotFound = nil
		} else {
			match++
		}
	} else {
		dst.UriNotFound = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.InvalidBlockchain = nil
		dst.InvalidNetwork = nil
		dst.InvalidPagination = nil
		dst.InvalidXpub = nil
		dst.LimitGreaterThanAllowed = nil
		dst.UriNotFound = nil

		return fmt.Errorf("Data matches more than one schema in oneOf(DeriveAndSyncNewChangeAddressesE400)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("Data failed to match schemas in oneOf(DeriveAndSyncNewChangeAddressesE400)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src DeriveAndSyncNewChangeAddressesE400) MarshalJSON() ([]byte, error) {
	if src.InvalidBlockchain != nil {
		return json.Marshal(&src.InvalidBlockchain)
	}

	if src.InvalidNetwork != nil {
		return json.Marshal(&src.InvalidNetwork)
	}

	if src.InvalidPagination != nil {
		return json.Marshal(&src.InvalidPagination)
	}

	if src.InvalidXpub != nil {
		return json.Marshal(&src.InvalidXpub)
	}

	if src.LimitGreaterThanAllowed != nil {
		return json.Marshal(&src.LimitGreaterThanAllowed)
	}

	if src.UriNotFound != nil {
		return json.Marshal(&src.UriNotFound)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *DeriveAndSyncNewChangeAddressesE400) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.InvalidBlockchain != nil {
		return obj.InvalidBlockchain
	}

	if obj.InvalidNetwork != nil {
		return obj.InvalidNetwork
	}

	if obj.InvalidPagination != nil {
		return obj.InvalidPagination
	}

	if obj.InvalidXpub != nil {
		return obj.InvalidXpub
	}

	if obj.LimitGreaterThanAllowed != nil {
		return obj.LimitGreaterThanAllowed
	}

	if obj.UriNotFound != nil {
		return obj.UriNotFound
	}

	// all schemas are nil
	return nil
}

type NullableDeriveAndSyncNewChangeAddressesE400 struct {
	value *DeriveAndSyncNewChangeAddressesE400
	isSet bool
}

func (v NullableDeriveAndSyncNewChangeAddressesE400) Get() *DeriveAndSyncNewChangeAddressesE400 {
	return v.value
}

func (v *NullableDeriveAndSyncNewChangeAddressesE400) Set(val *DeriveAndSyncNewChangeAddressesE400) {
	v.value = val
	v.isSet = true
}

func (v NullableDeriveAndSyncNewChangeAddressesE400) IsSet() bool {
	return v.isSet
}

func (v *NullableDeriveAndSyncNewChangeAddressesE400) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeriveAndSyncNewChangeAddressesE400(val *DeriveAndSyncNewChangeAddressesE400) *NullableDeriveAndSyncNewChangeAddressesE400 {
	return &NullableDeriveAndSyncNewChangeAddressesE400{value: val, isSet: true}
}

func (v NullableDeriveAndSyncNewChangeAddressesE400) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeriveAndSyncNewChangeAddressesE400) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


