/*
 * CryptoAPIs
 *
 * Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * API version: 2.0.0
 * Contact: developers@cryptoapis.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptoapis

import (
	"encoding/json"
)

// ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash Bitcoin Cash
type ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash struct {
	// Represents the time at which a particular transaction can be added to the blockchain.
	Locktime int32 `json:"locktime"`
	// Represents the total size of this transaction.
	Size int32 `json:"size"`
	// Represents transaction version number.
	Version int32 `json:"version"`
	// Represents the transaction inputs.
	Vin []ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCashVin `json:"vin"`
	// Represents the transaction outputs.
	Vout []ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCashVout `json:"vout"`
}

// NewListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash instantiates a new ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash(locktime int32, size int32, version int32, vin []ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCashVin, vout []ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCashVout) *ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash {
	this := ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash{}
	this.Locktime = locktime
	this.Size = size
	this.Version = version
	this.Vin = vin
	this.Vout = vout
	return &this
}

// NewListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCashWithDefaults instantiates a new ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCashWithDefaults() *ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash {
	this := ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash{}
	return &this
}

// GetLocktime returns the Locktime field value
func (o *ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash) GetLocktime() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Locktime
}

// GetLocktimeOk returns a tuple with the Locktime field value
// and a boolean to check if the value has been set.
func (o *ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash) GetLocktimeOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Locktime, true
}

// SetLocktime sets field value
func (o *ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash) SetLocktime(v int32) {
	o.Locktime = v
}

// GetSize returns the Size field value
func (o *ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash) GetSizeOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash) SetSize(v int32) {
	o.Size = v
}

// GetVersion returns the Version field value
func (o *ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash) GetVersionOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash) SetVersion(v int32) {
	o.Version = v
}

// GetVin returns the Vin field value
func (o *ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash) GetVin() []ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCashVin {
	if o == nil {
		var ret []ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCashVin
		return ret
	}

	return o.Vin
}

// GetVinOk returns a tuple with the Vin field value
// and a boolean to check if the value has been set.
func (o *ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash) GetVinOk() (*[]ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCashVin, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Vin, true
}

// SetVin sets field value
func (o *ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash) SetVin(v []ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCashVin) {
	o.Vin = v
}

// GetVout returns the Vout field value
func (o *ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash) GetVout() []ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCashVout {
	if o == nil {
		var ret []ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCashVout
		return ret
	}

	return o.Vout
}

// GetVoutOk returns a tuple with the Vout field value
// and a boolean to check if the value has been set.
func (o *ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash) GetVoutOk() (*[]ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCashVout, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Vout, true
}

// SetVout sets field value
func (o *ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash) SetVout(v []ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCashVout) {
	o.Vout = v
}

func (o ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["locktime"] = o.Locktime
	}
	if true {
		toSerialize["size"] = o.Size
	}
	if true {
		toSerialize["version"] = o.Version
	}
	if true {
		toSerialize["vin"] = o.Vin
	}
	if true {
		toSerialize["vout"] = o.Vout
	}
	return json.Marshal(toSerialize)
}

type NullableListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash struct {
	value *ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash
	isSet bool
}

func (v NullableListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash) Get() *ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash {
	return v.value
}

func (v *NullableListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash) Set(val *ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash) {
	v.value = val
	v.isSet = true
}

func (v NullableListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash) IsSet() bool {
	return v.isSet
}

func (v *NullableListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash(val *ListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash) *NullableListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash {
	return &NullableListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash{value: val, isSet: true}
}

func (v NullableListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListTransactionsByBlockHashResponseItemBlockchainSpecificBitcoinCash) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


