/*
CryptoAPIs

Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.

API version: 2.0.0
Contact: developers@cryptoapis.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cryptoapis

import (
	"encoding/json"
)

// DecodeRawTransactionHexRISB2Vout struct for DecodeRawTransactionHexRISB2Vout
type DecodeRawTransactionHexRISB2Vout struct {
	ScriptPubKey DecodeRawTransactionHexRISB2ScriptPubKey `json:"scriptPubKey"`
	// Represents the sent/received amount.
	Value *string `json:"value,omitempty"`
}

// NewDecodeRawTransactionHexRISB2Vout instantiates a new DecodeRawTransactionHexRISB2Vout object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDecodeRawTransactionHexRISB2Vout(scriptPubKey DecodeRawTransactionHexRISB2ScriptPubKey) *DecodeRawTransactionHexRISB2Vout {
	this := DecodeRawTransactionHexRISB2Vout{}
	this.ScriptPubKey = scriptPubKey
	return &this
}

// NewDecodeRawTransactionHexRISB2VoutWithDefaults instantiates a new DecodeRawTransactionHexRISB2Vout object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDecodeRawTransactionHexRISB2VoutWithDefaults() *DecodeRawTransactionHexRISB2Vout {
	this := DecodeRawTransactionHexRISB2Vout{}
	return &this
}

// GetScriptPubKey returns the ScriptPubKey field value
func (o *DecodeRawTransactionHexRISB2Vout) GetScriptPubKey() DecodeRawTransactionHexRISB2ScriptPubKey {
	if o == nil {
		var ret DecodeRawTransactionHexRISB2ScriptPubKey
		return ret
	}

	return o.ScriptPubKey
}

// GetScriptPubKeyOk returns a tuple with the ScriptPubKey field value
// and a boolean to check if the value has been set.
func (o *DecodeRawTransactionHexRISB2Vout) GetScriptPubKeyOk() (*DecodeRawTransactionHexRISB2ScriptPubKey, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScriptPubKey, true
}

// SetScriptPubKey sets field value
func (o *DecodeRawTransactionHexRISB2Vout) SetScriptPubKey(v DecodeRawTransactionHexRISB2ScriptPubKey) {
	o.ScriptPubKey = v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *DecodeRawTransactionHexRISB2Vout) GetValue() string {
	if o == nil || o.Value == nil {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DecodeRawTransactionHexRISB2Vout) GetValueOk() (*string, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *DecodeRawTransactionHexRISB2Vout) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *DecodeRawTransactionHexRISB2Vout) SetValue(v string) {
	o.Value = &v
}

func (o DecodeRawTransactionHexRISB2Vout) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["scriptPubKey"] = o.ScriptPubKey
	}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableDecodeRawTransactionHexRISB2Vout struct {
	value *DecodeRawTransactionHexRISB2Vout
	isSet bool
}

func (v NullableDecodeRawTransactionHexRISB2Vout) Get() *DecodeRawTransactionHexRISB2Vout {
	return v.value
}

func (v *NullableDecodeRawTransactionHexRISB2Vout) Set(val *DecodeRawTransactionHexRISB2Vout) {
	v.value = val
	v.isSet = true
}

func (v NullableDecodeRawTransactionHexRISB2Vout) IsSet() bool {
	return v.isSet
}

func (v *NullableDecodeRawTransactionHexRISB2Vout) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDecodeRawTransactionHexRISB2Vout(val *DecodeRawTransactionHexRISB2Vout) *NullableDecodeRawTransactionHexRISB2Vout {
	return &NullableDecodeRawTransactionHexRISB2Vout{value: val, isSet: true}
}

func (v NullableDecodeRawTransactionHexRISB2Vout) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDecodeRawTransactionHexRISB2Vout) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


